// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sync.proto

package sync

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriteRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Deleted              bool     `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{0}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *WriteRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *WriteRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WriteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *WriteRequest) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type WriteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{1}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReadRequest struct {
	First                int64    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 int64    `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{2}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ReadRequest) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *ReadRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type ReadResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Deleted              bool     `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{3}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReadResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ReadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type GetDifferenceRequest struct {
	Local                int64    `protobuf:"varint,1,opt,name=local,proto3" json:"local,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDifferenceRequest) Reset()         { *m = GetDifferenceRequest{} }
func (m *GetDifferenceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDifferenceRequest) ProtoMessage()    {}
func (*GetDifferenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{4}
}

func (m *GetDifferenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDifferenceRequest.Unmarshal(m, b)
}
func (m *GetDifferenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDifferenceRequest.Marshal(b, m, deterministic)
}
func (m *GetDifferenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDifferenceRequest.Merge(m, src)
}
func (m *GetDifferenceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDifferenceRequest.Size(m)
}
func (m *GetDifferenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDifferenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDifferenceRequest proto.InternalMessageInfo

func (m *GetDifferenceRequest) GetLocal() int64 {
	if m != nil {
		return m.Local
	}
	return 0
}

func (m *GetDifferenceRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type GetDifferenceResponse struct {
	Difference           int64    `protobuf:"varint,1,opt,name=difference,proto3" json:"difference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDifferenceResponse) Reset()         { *m = GetDifferenceResponse{} }
func (m *GetDifferenceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDifferenceResponse) ProtoMessage()    {}
func (*GetDifferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{5}
}

func (m *GetDifferenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDifferenceResponse.Unmarshal(m, b)
}
func (m *GetDifferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDifferenceResponse.Marshal(b, m, deterministic)
}
func (m *GetDifferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDifferenceResponse.Merge(m, src)
}
func (m *GetDifferenceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDifferenceResponse.Size(m)
}
func (m *GetDifferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDifferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDifferenceResponse proto.InternalMessageInfo

func (m *GetDifferenceResponse) GetDifference() int64 {
	if m != nil {
		return m.Difference
	}
	return 0
}

type CheckRequest struct {
	Table1               string   `protobuf:"bytes,1,opt,name=table1,proto3" json:"table1,omitempty"`
	Table2               string   `protobuf:"bytes,2,opt,name=table2,proto3" json:"table2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{6}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetTable1() string {
	if m != nil {
		return m.Table1
	}
	return ""
}

func (m *CheckRequest) GetTable2() string {
	if m != nil {
		return m.Table2
	}
	return ""
}

type CheckResponse struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{7}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type DeleteRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *DeleteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RestoreRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{10}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RestoreRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type RestoreResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{11}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*WriteRequest)(nil), "WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "WriteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*GetDifferenceRequest)(nil), "GetDifferenceRequest")
	proto.RegisterType((*GetDifferenceResponse)(nil), "GetDifferenceResponse")
	proto.RegisterType((*CheckRequest)(nil), "CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "CheckResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*RestoreRequest)(nil), "RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "RestoreResponse")
}

func init() {
	proto.RegisterFile("proto/sync.proto", fileDescriptor_56dcb3cab7b591a9)
}

var fileDescriptor_56dcb3cab7b591a9 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0xc6, 0x8e, 0xdb, 0x0e, 0xb6, 0x53, 0xad, 0xda, 0xc8, 0xf2, 0x01, 0x45, 0x96, 0x2a,
	0xb9, 0x14, 0x2d, 0x50, 0x0e, 0x1c, 0x40, 0x3d, 0x40, 0x11, 0x27, 0x2e, 0xcb, 0x81, 0xb3, 0xbb,
	0x9e, 0x10, 0x0b, 0x63, 0x07, 0xef, 0x5a, 0x22, 0x3f, 0xc0, 0x5f, 0xf0, 0xaf, 0x28, 0xeb, 0xb5,
	0xb3, 0x8e, 0x22, 0x22, 0xa1, 0xde, 0xf6, 0x4d, 0x76, 0x67, 0xde, 0xbc, 0xf7, 0x62, 0x38, 0x5f,
	0x37, 0xb5, 0xaa, 0x5f, 0xc8, 0x4d, 0x25, 0x98, 0x3e, 0x26, 0xbf, 0x09, 0xf8, 0x5f, 0x9b, 0x42,
	0x21, 0xc7, 0x9f, 0x2d, 0x4a, 0x45, 0x2f, 0x60, 0x2a, 0xea, 0xb6, 0x52, 0x11, 0x59, 0x90, 0xd4,
	0xe1, 0x1d, 0xa0, 0x73, 0xf0, 0xb2, 0x56, 0xad, 0xea, 0x26, 0x9a, 0x2c, 0x48, 0x7a, 0xc6, 0x0d,
	0xa2, 0x11, 0x9c, 0xfc, 0x40, 0x29, 0xb3, 0x6f, 0x18, 0x39, 0xfa, 0x87, 0x1e, 0x6e, 0xfb, 0xa8,
	0xec, 0xa1, 0xc4, 0xc8, 0xd5, 0xf5, 0x0e, 0x6c, 0xef, 0xe7, 0x58, 0xa2, 0xc2, 0x3c, 0x9a, 0x2e,
	0x48, 0x7a, 0xca, 0x7b, 0x98, 0x5c, 0x43, 0x60, 0x78, 0xc8, 0x75, 0x5d, 0x49, 0x7d, 0x55, 0xb6,
	0x42, 0xa0, 0x94, 0x9a, 0xca, 0x29, 0xef, 0x61, 0xf2, 0x19, 0x9e, 0x70, 0xcc, 0x72, 0x8b, 0xf1,
	0xb2, 0x68, 0xe4, 0xc0, 0x58, 0x03, 0x4a, 0xc1, 0x2d, 0x33, 0xa9, 0x34, 0x5f, 0x87, 0xeb, 0xf3,
	0x8e, 0x93, 0x63, 0x71, 0x4a, 0xd6, 0xe0, 0x77, 0xed, 0xcc, 0xe0, 0xc7, 0x52, 0xc0, 0xda, 0xd5,
	0x1d, 0xef, 0xfa, 0x1e, 0x2e, 0x3e, 0xa1, 0xba, 0x2f, 0x96, 0x4b, 0x6c, 0xb0, 0x12, 0xb6, 0xf6,
	0x65, 0x2d, 0xb2, 0xb2, 0x9f, 0xac, 0xc1, 0x8e, 0xf5, 0xc4, 0x66, 0xfd, 0x06, 0x2e, 0xf7, 0x7a,
	0x18, 0xfa, 0x4f, 0x01, 0xf2, 0xa1, 0x6a, 0x3a, 0x59, 0x95, 0xe4, 0x0e, 0xfc, 0x0f, 0x2b, 0x14,
	0xdf, 0xfb, 0xa1, 0x73, 0xf0, 0x74, 0xc7, 0x57, 0xfa, 0xee, 0x19, 0x37, 0x68, 0xa8, 0xdf, 0xf6,
	0x0b, 0x77, 0x28, 0xb9, 0x82, 0xc0, 0xbc, 0xdf, 0xe9, 0xd5, 0xf1, 0x23, 0x36, 0xbf, 0xb7, 0x10,
	0xdc, 0xeb, 0x75, 0xff, 0x1d, 0xac, 0x83, 0x31, 0x49, 0x9e, 0x41, 0xd8, 0x3f, 0x3e, 0x9a, 0x86,
	0x77, 0x10, 0x72, 0x94, 0xaa, 0x6e, 0xfe, 0x6b, 0xd2, 0x0d, 0xcc, 0x86, 0xd7, 0xc7, 0x46, 0xdd,
	0xfe, 0x99, 0x80, 0xfb, 0x65, 0x53, 0x09, 0x9a, 0xc2, 0x54, 0x87, 0x95, 0x06, 0xcc, 0xfe, 0xf3,
	0xc4, 0x21, 0x1b, 0x65, 0x38, 0x25, 0xf4, 0x0e, 0x82, 0x91, 0x4d, 0xf4, 0x92, 0x1d, 0xb2, 0x3e,
	0x9e, 0xb3, 0xc3, 0x6e, 0x5e, 0x81, 0xbb, 0x0d, 0x27, 0xf5, 0x99, 0x15, 0xf9, 0x38, 0x60, 0x76,
	0x62, 0x5f, 0x12, 0x7a, 0x03, 0xa0, 0x4d, 0xf9, 0xf8, 0xab, 0x90, 0x8a, 0x06, 0xcc, 0x76, 0x38,
	0x0e, 0xd9, 0xd8, 0xb0, 0x6b, 0xf0, 0x3a, 0x75, 0x69, 0xc8, 0x46, 0x1e, 0xc5, 0x33, 0xb6, 0x27,
	0xfb, 0x73, 0x38, 0x31, 0xf2, 0xd0, 0x19, 0x1b, 0xcb, 0x1c, 0x9f, 0xb3, 0x3d, 0xe5, 0x1e, 0x3c,
	0xfd, 0x4d, 0x79, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x02, 0x09, 0xee, 0xa2, 0x67, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SyncClient is the client API for Sync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (Sync_WriteClient, error)
	GetDifference(ctx context.Context, in *GetDifferenceRequest, opts ...grpc.CallOption) (*GetDifferenceResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Sync_ReadClient, error)
	CheckExist(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
}

type syncClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncClient(cc grpc.ClientConnInterface) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) Write(ctx context.Context, opts ...grpc.CallOption) (Sync_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sync_serviceDesc.Streams[0], "/Sync/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncWriteClient{stream}
	return x, nil
}

type Sync_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*WriteResponse, error)
	grpc.ClientStream
}

type syncWriteClient struct {
	grpc.ClientStream
}

func (x *syncWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *syncWriteClient) CloseAndRecv() (*WriteResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncClient) GetDifference(ctx context.Context, in *GetDifferenceRequest, opts ...grpc.CallOption) (*GetDifferenceResponse, error) {
	out := new(GetDifferenceResponse)
	err := c.cc.Invoke(ctx, "/Sync/GetDifference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Sync_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sync_serviceDesc.Streams[1], "/Sync/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sync_ReadClient interface {
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type syncReadClient struct {
	grpc.ClientStream
}

func (x *syncReadClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncClient) CheckExist(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/Sync/CheckExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/Sync/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/Sync/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServer is the server API for Sync service.
type SyncServer interface {
	Write(Sync_WriteServer) error
	GetDifference(context.Context, *GetDifferenceRequest) (*GetDifferenceResponse, error)
	Read(*ReadRequest, Sync_ReadServer) error
	CheckExist(context.Context, *CheckRequest) (*CheckResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
}

// UnimplementedSyncServer can be embedded to have forward compatible implementations.
type UnimplementedSyncServer struct {
}

func (*UnimplementedSyncServer) Write(srv Sync_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedSyncServer) GetDifference(ctx context.Context, req *GetDifferenceRequest) (*GetDifferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDifference not implemented")
}
func (*UnimplementedSyncServer) Read(req *ReadRequest, srv Sync_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedSyncServer) CheckExist(ctx context.Context, req *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExist not implemented")
}
func (*UnimplementedSyncServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedSyncServer) Restore(ctx context.Context, req *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

func RegisterSyncServer(s *grpc.Server, srv SyncServer) {
	s.RegisterService(&_Sync_serviceDesc, srv)
}

func _Sync_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServer).Write(&syncWriteServer{stream})
}

type Sync_WriteServer interface {
	SendAndClose(*WriteResponse) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type syncWriteServer struct {
	grpc.ServerStream
}

func (x *syncWriteServer) SendAndClose(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *syncWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Sync_GetDifference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDifferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).GetDifference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sync/GetDifference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).GetDifference(ctx, req.(*GetDifferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServer).Read(m, &syncReadServer{stream})
}

type Sync_ReadServer interface {
	Send(*ReadResponse) error
	grpc.ServerStream
}

type syncReadServer struct {
	grpc.ServerStream
}

func (x *syncReadServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Sync_CheckExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).CheckExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sync/CheckExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).CheckExist(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sync/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sync/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Sync",
	HandlerType: (*SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDifference",
			Handler:    _Sync_GetDifference_Handler,
		},
		{
			MethodName: "CheckExist",
			Handler:    _Sync_CheckExist_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Sync_Delete_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Sync_Restore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Sync_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Sync_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sync.proto",
}
