// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CheckResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{5}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{6}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetAllUserRequest struct {
	IsAdmin              bool     `protobuf:"varint,1,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserRequest) Reset()         { *m = GetAllUserRequest{} }
func (m *GetAllUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllUserRequest) ProtoMessage()    {}
func (*GetAllUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{7}
}

func (m *GetAllUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserRequest.Unmarshal(m, b)
}
func (m *GetAllUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserRequest.Marshal(b, m, deterministic)
}
func (m *GetAllUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserRequest.Merge(m, src)
}
func (m *GetAllUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllUserRequest.Size(m)
}
func (m *GetAllUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserRequest proto.InternalMessageInfo

func (m *GetAllUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash         string   `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type AuthorizedUser struct {
	IsAdmin              bool     `protobuf:"varint,1,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Birthday             string   `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Fb                   string   `protobuf:"bytes,7,opt,name=fb,proto3" json:"fb,omitempty"`
	Insta                string   `protobuf:"bytes,8,opt,name=insta,proto3" json:"insta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizedUser) Reset()         { *m = AuthorizedUser{} }
func (m *AuthorizedUser) String() string { return proto.CompactTextString(m) }
func (*AuthorizedUser) ProtoMessage()    {}
func (*AuthorizedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{9}
}

func (m *AuthorizedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedUser.Unmarshal(m, b)
}
func (m *AuthorizedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedUser.Marshal(b, m, deterministic)
}
func (m *AuthorizedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedUser.Merge(m, src)
}
func (m *AuthorizedUser) XXX_Size() int {
	return xxx_messageInfo_AuthorizedUser.Size(m)
}
func (m *AuthorizedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedUser.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedUser proto.InternalMessageInfo

func (m *AuthorizedUser) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *AuthorizedUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthorizedUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthorizedUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AuthorizedUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AuthorizedUser) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *AuthorizedUser) GetFb() string {
	if m != nil {
		return m.Fb
	}
	return ""
}

func (m *AuthorizedUser) GetInsta() string {
	if m != nil {
		return m.Insta
	}
	return ""
}

type UpdateEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{10}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateEmailResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailResponse) Reset()         { *m = UpdateEmailResponse{} }
func (m *UpdateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailResponse) ProtoMessage()    {}
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11}
}

func (m *UpdateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailResponse.Unmarshal(m, b)
}
func (m *UpdateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailResponse.Merge(m, src)
}
func (m *UpdateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailResponse.Size(m)
}
func (m *UpdateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailResponse proto.InternalMessageInfo

func (m *UpdateEmailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateEmailResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateAvatarRequest struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAvatarRequest) Reset()         { *m = UpdateAvatarRequest{} }
func (m *UpdateAvatarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAvatarRequest) ProtoMessage()    {}
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{12}
}

func (m *UpdateAvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAvatarRequest.Unmarshal(m, b)
}
func (m *UpdateAvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAvatarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAvatarRequest.Merge(m, src)
}
func (m *UpdateAvatarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAvatarRequest.Size(m)
}
func (m *UpdateAvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAvatarRequest proto.InternalMessageInfo

func (m *UpdateAvatarRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UpdateAvatarResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAvatarResponse) Reset()         { *m = UpdateAvatarResponse{} }
func (m *UpdateAvatarResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAvatarResponse) ProtoMessage()    {}
func (*UpdateAvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{13}
}

func (m *UpdateAvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAvatarResponse.Unmarshal(m, b)
}
func (m *UpdateAvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAvatarResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAvatarResponse.Merge(m, src)
}
func (m *UpdateAvatarResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAvatarResponse.Size(m)
}
func (m *UpdateAvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAvatarResponse proto.InternalMessageInfo

func (m *UpdateAvatarResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateAvatarResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UpdatePhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePhoneRequest) Reset()         { *m = UpdatePhoneRequest{} }
func (m *UpdatePhoneRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePhoneRequest) ProtoMessage()    {}
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{14}
}

func (m *UpdatePhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhoneRequest.Unmarshal(m, b)
}
func (m *UpdatePhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhoneRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhoneRequest.Merge(m, src)
}
func (m *UpdatePhoneRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePhoneRequest.Size(m)
}
func (m *UpdatePhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhoneRequest proto.InternalMessageInfo

func (m *UpdatePhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UpdatePhoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePhoneResponse) Reset()         { *m = UpdatePhoneResponse{} }
func (m *UpdatePhoneResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePhoneResponse) ProtoMessage()    {}
func (*UpdatePhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{15}
}

func (m *UpdatePhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhoneResponse.Unmarshal(m, b)
}
func (m *UpdatePhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhoneResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhoneResponse.Merge(m, src)
}
func (m *UpdatePhoneResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePhoneResponse.Size(m)
}
func (m *UpdatePhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhoneResponse proto.InternalMessageInfo

func (m *UpdatePhoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdatePhoneResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UpdateBirthdayRequest struct {
	Birthday             string   `protobuf:"bytes,1,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBirthdayRequest) Reset()         { *m = UpdateBirthdayRequest{} }
func (m *UpdateBirthdayRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBirthdayRequest) ProtoMessage()    {}
func (*UpdateBirthdayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{16}
}

func (m *UpdateBirthdayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBirthdayRequest.Unmarshal(m, b)
}
func (m *UpdateBirthdayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBirthdayRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBirthdayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBirthdayRequest.Merge(m, src)
}
func (m *UpdateBirthdayRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBirthdayRequest.Size(m)
}
func (m *UpdateBirthdayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBirthdayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBirthdayRequest proto.InternalMessageInfo

func (m *UpdateBirthdayRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type UpdateBirthdayResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Birth                string   `protobuf:"bytes,2,opt,name=birth,proto3" json:"birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBirthdayResponse) Reset()         { *m = UpdateBirthdayResponse{} }
func (m *UpdateBirthdayResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBirthdayResponse) ProtoMessage()    {}
func (*UpdateBirthdayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{17}
}

func (m *UpdateBirthdayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBirthdayResponse.Unmarshal(m, b)
}
func (m *UpdateBirthdayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBirthdayResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBirthdayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBirthdayResponse.Merge(m, src)
}
func (m *UpdateBirthdayResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBirthdayResponse.Size(m)
}
func (m *UpdateBirthdayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBirthdayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBirthdayResponse proto.InternalMessageInfo

func (m *UpdateBirthdayResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateBirthdayResponse) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

type UpdateFbRequest struct {
	Fb                   string   `protobuf:"bytes,1,opt,name=fb,proto3" json:"fb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFbRequest) Reset()         { *m = UpdateFbRequest{} }
func (m *UpdateFbRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFbRequest) ProtoMessage()    {}
func (*UpdateFbRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{18}
}

func (m *UpdateFbRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFbRequest.Unmarshal(m, b)
}
func (m *UpdateFbRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFbRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFbRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFbRequest.Merge(m, src)
}
func (m *UpdateFbRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFbRequest.Size(m)
}
func (m *UpdateFbRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFbRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFbRequest proto.InternalMessageInfo

func (m *UpdateFbRequest) GetFb() string {
	if m != nil {
		return m.Fb
	}
	return ""
}

type UpdateFbResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Fb                   string   `protobuf:"bytes,2,opt,name=fb,proto3" json:"fb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFbResponse) Reset()         { *m = UpdateFbResponse{} }
func (m *UpdateFbResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFbResponse) ProtoMessage()    {}
func (*UpdateFbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{19}
}

func (m *UpdateFbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFbResponse.Unmarshal(m, b)
}
func (m *UpdateFbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFbResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFbResponse.Merge(m, src)
}
func (m *UpdateFbResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFbResponse.Size(m)
}
func (m *UpdateFbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFbResponse proto.InternalMessageInfo

func (m *UpdateFbResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateFbResponse) GetFb() string {
	if m != nil {
		return m.Fb
	}
	return ""
}

type UpdateInstaRequest struct {
	Insta                string   `protobuf:"bytes,1,opt,name=insta,proto3" json:"insta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstaRequest) Reset()         { *m = UpdateInstaRequest{} }
func (m *UpdateInstaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInstaRequest) ProtoMessage()    {}
func (*UpdateInstaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{20}
}

func (m *UpdateInstaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstaRequest.Unmarshal(m, b)
}
func (m *UpdateInstaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInstaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstaRequest.Merge(m, src)
}
func (m *UpdateInstaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInstaRequest.Size(m)
}
func (m *UpdateInstaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstaRequest proto.InternalMessageInfo

func (m *UpdateInstaRequest) GetInsta() string {
	if m != nil {
		return m.Insta
	}
	return ""
}

type UpdateInstaResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Insta                string   `protobuf:"bytes,2,opt,name=insta,proto3" json:"insta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstaResponse) Reset()         { *m = UpdateInstaResponse{} }
func (m *UpdateInstaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInstaResponse) ProtoMessage()    {}
func (*UpdateInstaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{21}
}

func (m *UpdateInstaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstaResponse.Unmarshal(m, b)
}
func (m *UpdateInstaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstaResponse.Marshal(b, m, deterministic)
}
func (m *UpdateInstaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstaResponse.Merge(m, src)
}
func (m *UpdateInstaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInstaResponse.Size(m)
}
func (m *UpdateInstaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstaResponse proto.InternalMessageInfo

func (m *UpdateInstaResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateInstaResponse) GetInsta() string {
	if m != nil {
		return m.Insta
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*CheckRequest)(nil), "CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "CheckResponse")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*GetUserRequest)(nil), "GetUserRequest")
	proto.RegisterType((*GetAllUserRequest)(nil), "GetAllUserRequest")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*AuthorizedUser)(nil), "AuthorizedUser")
	proto.RegisterType((*UpdateEmailRequest)(nil), "UpdateEmailRequest")
	proto.RegisterType((*UpdateEmailResponse)(nil), "UpdateEmailResponse")
	proto.RegisterType((*UpdateAvatarRequest)(nil), "UpdateAvatarRequest")
	proto.RegisterType((*UpdateAvatarResponse)(nil), "UpdateAvatarResponse")
	proto.RegisterType((*UpdatePhoneRequest)(nil), "UpdatePhoneRequest")
	proto.RegisterType((*UpdatePhoneResponse)(nil), "UpdatePhoneResponse")
	proto.RegisterType((*UpdateBirthdayRequest)(nil), "UpdateBirthdayRequest")
	proto.RegisterType((*UpdateBirthdayResponse)(nil), "UpdateBirthdayResponse")
	proto.RegisterType((*UpdateFbRequest)(nil), "UpdateFbRequest")
	proto.RegisterType((*UpdateFbResponse)(nil), "UpdateFbResponse")
	proto.RegisterType((*UpdateInstaRequest)(nil), "UpdateInstaRequest")
	proto.RegisterType((*UpdateInstaResponse)(nil), "UpdateInstaResponse")
}

func init() {
	proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144)
}

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x4d, 0xd2, 0xa4, 0x43, 0x6e, 0xdd, 0xa6, 0xc5, 0xf2, 0x13, 0xac, 0x50, 0xc5, 0xad,
	0x5b, 0x44, 0x5f, 0x90, 0x40, 0x42, 0x29, 0xea, 0x4d, 0xe2, 0x01, 0x45, 0xea, 0x3b, 0x9b, 0x7a,
	0x5b, 0x5b, 0x4d, 0xed, 0xe0, 0xdd, 0x14, 0xc1, 0xc7, 0xf1, 0x05, 0x7c, 0x14, 0xf2, 0xde, 0xbc,
	0x9b, 0xf4, 0x12, 0xc1, 0x5b, 0xc6, 0x9e, 0x3d, 0x67, 0xce, 0xec, 0x99, 0x71, 0x60, 0x30, 0x2b,
	0x0b, 0x51, 0xec, 0xd1, 0xb9, 0x48, 0x89, 0xfc, 0x89, 0x8f, 0xa0, 0xf3, 0xa5, 0xb8, 0xcc, 0xf2,
	0x31, 0xfb, 0x3e, 0x67, 0x5c, 0xa0, 0x18, 0xda, 0x73, 0xce, 0xca, 0x9c, 0x5e, 0xb3, 0x28, 0x78,
	0x1a, 0xbc, 0x58, 0x1f, 0xdb, 0xb8, 0x7a, 0x37, 0xa3, 0x9c, 0xff, 0x28, 0xca, 0x24, 0x0a, 0xd5,
	0x3b, 0x13, 0xe3, 0x4f, 0xd0, 0xd5, 0x38, 0x7c, 0x56, 0xe4, 0x9c, 0xa1, 0x08, 0x5a, 0x7c, 0x7e,
	0x7e, 0xce, 0x38, 0x97, 0x38, 0xed, 0xb1, 0x09, 0xd1, 0x10, 0x9a, 0xa2, 0xb8, 0x62, 0xb9, 0xc6,
	0x50, 0x01, 0x7e, 0x0e, 0x9d, 0xcf, 0x29, 0x3b, 0xbf, 0x32, 0x85, 0xd8, 0xac, 0xc0, 0xcd, 0x1a,
	0x41, 0x57, 0x67, 0x69, 0x9a, 0x21, 0x34, 0x6f, 0xe8, 0x34, 0x4b, 0x34, 0x89, 0x0a, 0x3c, 0x15,
	0xa1, 0xaf, 0x02, 0x9f, 0x42, 0x7f, 0xcc, 0x2e, 0x33, 0x2e, 0x58, 0xf9, 0xbf, 0xa2, 0x0f, 0x60,
	0x50, 0x43, 0xfd, 0xa3, 0xee, 0x37, 0xd0, 0x3b, 0x66, 0xe2, 0x8c, 0xaf, 0x54, 0x0d, 0xde, 0x85,
	0x8d, 0x63, 0x26, 0x46, 0xd3, 0xa9, 0x7b, 0x20, 0x82, 0x56, 0xc6, 0x47, 0xc9, 0x75, 0x96, 0x1b,
	0x4a, 0x1d, 0xe2, 0x6f, 0xd0, 0xa8, 0x12, 0xef, 0x15, 0x88, 0xa1, 0x63, 0x04, 0x9d, 0x50, 0x9e,
	0xea, 0xea, 0xbc, 0x67, 0x2e, 0xc3, 0x23, 0x9f, 0xe1, 0x4f, 0x00, 0xbd, 0xd1, 0x5c, 0xa4, 0x45,
	0x99, 0xfd, 0x62, 0x89, 0x24, 0xbb, 0xb3, 0x9c, 0xfb, 0xae, 0xa5, 0xea, 0x0e, 0xbb, 0xa6, 0xd9,
	0x54, 0x12, 0xac, 0x8f, 0x55, 0x80, 0xb6, 0x61, 0x8d, 0xde, 0x50, 0x41, 0xcb, 0xa8, 0x21, 0x1f,
	0xeb, 0xa8, 0xca, 0x9e, 0xa5, 0x45, 0xce, 0xa2, 0xa6, 0xca, 0x96, 0x41, 0x85, 0x3f, 0xc9, 0x4a,
	0x91, 0x26, 0xf4, 0x67, 0xb4, 0xa6, 0xf0, 0x4d, 0x8c, 0x7a, 0x10, 0x5e, 0x4c, 0xa2, 0x96, 0x7c,
	0x1a, 0x5e, 0x4c, 0x2a, 0x84, 0x2c, 0xe7, 0x82, 0x46, 0x6d, 0x85, 0x20, 0x03, 0xfc, 0x0a, 0xd0,
	0xd9, 0x2c, 0xa1, 0x82, 0x1d, 0x56, 0xf4, 0x8e, 0x17, 0x55, 0x6d, 0x81, 0x53, 0x1b, 0x3e, 0x84,
	0x4d, 0x2f, 0x77, 0x15, 0x03, 0x28, 0x98, 0xd0, 0x85, 0xd9, 0x35, 0x30, 0x23, 0x29, 0xcd, 0x70,
	0xd6, 0xca, 0x03, 0x57, 0x39, 0x3e, 0x81, 0xa1, 0x9f, 0xfe, 0x20, 0x6d, 0x8d, 0x14, 0x7a, 0x48,
	0x56, 0xeb, 0xd7, 0xaa, 0x79, 0x8e, 0x56, 0xd5, 0xd9, 0xc0, 0xe9, 0x6c, 0xad, 0x55, 0xe7, 0xae,
	0xa2, 0x55, 0xc1, 0x84, 0x2e, 0xcc, 0x3e, 0x6c, 0x29, 0x98, 0x03, 0x7d, 0x2d, 0x8e, 0xe7, 0xed,
	0xcd, 0x05, 0xfe, 0xcd, 0xe1, 0x13, 0xd8, 0x5e, 0x3c, 0xb4, 0x0a, 0xbd, 0x3c, 0x6f, 0xe8, 0x65,
	0x80, 0x9f, 0x41, 0x5f, 0x21, 0x1d, 0x4d, 0x0c, 0xb1, 0xb2, 0x45, 0x60, 0x6c, 0x81, 0x3f, 0xc2,
	0xa0, 0x4e, 0x79, 0x90, 0x46, 0x9d, 0x0e, 0xed, 0x69, 0xdb, 0xd2, 0xd3, 0xca, 0x4d, 0x4e, 0x4b,
	0x95, 0xd5, 0x02, 0xd7, 0x6a, 0xb6, 0xa5, 0x3a, 0x77, 0x15, 0x4d, 0x0a, 0x26, 0x74, 0x60, 0xde,
	0xfd, 0x6e, 0x40, 0xa3, 0x1a, 0x40, 0xb4, 0x03, 0x4d, 0xb9, 0x81, 0x51, 0x97, 0xb8, 0x1b, 0x3d,
	0xee, 0x11, 0x7f, 0x31, 0xef, 0x41, 0xdb, 0x2c, 0x2d, 0x34, 0x20, 0x0b, 0xab, 0x30, 0xde, 0x20,
	0x4b, 0x1b, 0x6d, 0x07, 0x9a, 0x72, 0xe7, 0xa2, 0x2e, 0x71, 0x37, 0x74, 0xdc, 0x23, 0xfe, 0x2a,
	0x7e, 0x0d, 0x2d, 0xbd, 0xc9, 0x50, 0x9f, 0xf8, 0x3b, 0x2d, 0xee, 0x93, 0x85, 0x25, 0xf1, 0x1e,
	0x1e, 0x3b, 0xc3, 0x83, 0x36, 0xc9, 0xf2, 0xd8, 0xc5, 0x43, 0x72, 0xdb, 0x7c, 0x7d, 0x80, 0x8e,
	0x3b, 0x00, 0xc8, 0x64, 0x79, 0xe3, 0x13, 0x6f, 0x91, 0x5b, 0xa7, 0xc4, 0xd2, 0x4a, 0x1f, 0x5b,
	0x5a, 0x77, 0x02, 0x2c, 0xad, 0x6f, 0xf5, 0x11, 0xf4, 0x7c, 0x17, 0xa2, 0x6d, 0x72, 0xab, 0x97,
	0xe3, 0x27, 0xe4, 0x0e, 0xbb, 0xee, 0x41, 0xdb, 0x78, 0x0b, 0x0d, 0xc8, 0x82, 0x13, 0xe3, 0x0d,
	0xb2, 0x64, 0x3c, 0x5b, 0xad, 0xb4, 0x88, 0xad, 0xd6, 0x35, 0x97, 0xad, 0xd6, 0x77, 0xd1, 0x4b,
	0x80, 0xfa, 0x3b, 0x81, 0x10, 0x59, 0xfa, 0x68, 0xc4, 0x4d, 0x52, 0x45, 0x6f, 0x83, 0xc9, 0x9a,
	0xfc, 0x23, 0xb0, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x07, 0x82, 0x07, 0x65, 0x1c, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*AuthorizedUser, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error)
	UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*UpdateAvatarResponse, error)
	UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error)
	UpdateBirthday(ctx context.Context, in *UpdateBirthdayRequest, opts ...grpc.CallOption) (*UpdateBirthdayResponse, error)
	UpdateFb(ctx context.Context, in *UpdateFbRequest, opts ...grpc.CallOption) (*UpdateFbResponse, error)
	UpdateInsta(ctx context.Context, in *UpdateInstaRequest, opts ...grpc.CallOption) (*UpdateInstaResponse, error)
	GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (Auth_GetAllUserClient, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/Auth/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*AuthorizedUser, error) {
	out := new(AuthorizedUser)
	err := c.cc.Invoke(ctx, "/Auth/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error) {
	out := new(UpdateEmailResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*UpdateAvatarResponse, error) {
	out := new(UpdateAvatarResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdateAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error) {
	out := new(UpdatePhoneResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdatePhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdateBirthday(ctx context.Context, in *UpdateBirthdayRequest, opts ...grpc.CallOption) (*UpdateBirthdayResponse, error) {
	out := new(UpdateBirthdayResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdateBirthday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdateFb(ctx context.Context, in *UpdateFbRequest, opts ...grpc.CallOption) (*UpdateFbResponse, error) {
	out := new(UpdateFbResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdateFb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UpdateInsta(ctx context.Context, in *UpdateInstaRequest, opts ...grpc.CallOption) (*UpdateInstaResponse, error) {
	out := new(UpdateInstaResponse)
	err := c.cc.Invoke(ctx, "/Auth/UpdateInsta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (Auth_GetAllUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Auth_serviceDesc.Streams[0], "/Auth/GetAllUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &authGetAllUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Auth_GetAllUserClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type authGetAllUserClient struct {
	grpc.ClientStream
}

func (x *authGetAllUserClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	GetUser(context.Context, *GetUserRequest) (*AuthorizedUser, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*UpdateEmailResponse, error)
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UpdateAvatarResponse, error)
	UpdatePhone(context.Context, *UpdatePhoneRequest) (*UpdatePhoneResponse, error)
	UpdateBirthday(context.Context, *UpdateBirthdayRequest) (*UpdateBirthdayResponse, error)
	UpdateFb(context.Context, *UpdateFbRequest) (*UpdateFbResponse, error)
	UpdateInsta(context.Context, *UpdateInstaRequest) (*UpdateInstaResponse, error)
	GetAllUser(*GetAllUserRequest, Auth_GetAllUserServer) error
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthServer) Check(ctx context.Context, req *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedAuthServer) GetUser(ctx context.Context, req *GetUserRequest) (*AuthorizedUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAuthServer) UpdateEmail(ctx context.Context, req *UpdateEmailRequest) (*UpdateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (*UnimplementedAuthServer) UpdateAvatar(ctx context.Context, req *UpdateAvatarRequest) (*UpdateAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAvatar not implemented")
}
func (*UnimplementedAuthServer) UpdatePhone(ctx context.Context, req *UpdatePhoneRequest) (*UpdatePhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhone not implemented")
}
func (*UnimplementedAuthServer) UpdateBirthday(ctx context.Context, req *UpdateBirthdayRequest) (*UpdateBirthdayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBirthday not implemented")
}
func (*UnimplementedAuthServer) UpdateFb(ctx context.Context, req *UpdateFbRequest) (*UpdateFbResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFb not implemented")
}
func (*UnimplementedAuthServer) UpdateInsta(ctx context.Context, req *UpdateInstaRequest) (*UpdateInstaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInsta not implemented")
}
func (*UnimplementedAuthServer) GetAllUser(req *GetAllUserRequest, srv Auth_GetAllUserServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllUser not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdateAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdateAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdatePhone(ctx, req.(*UpdatePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdateBirthday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBirthdayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdateBirthday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdateBirthday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdateBirthday(ctx, req.(*UpdateBirthdayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdateFb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdateFb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdateFb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdateFb(ctx, req.(*UpdateFbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UpdateInsta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UpdateInsta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/UpdateInsta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UpdateInsta(ctx, req.(*UpdateInstaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetAllUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllUserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServer).GetAllUser(m, &authGetAllUserServer{stream})
}

type Auth_GetAllUserServer interface {
	Send(*User) error
	grpc.ServerStream
}

type authGetAllUserServer struct {
	grpc.ServerStream
}

func (x *authGetAllUserServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Auth_Check_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Auth_GetUser_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _Auth_UpdateEmail_Handler,
		},
		{
			MethodName: "UpdateAvatar",
			Handler:    _Auth_UpdateAvatar_Handler,
		},
		{
			MethodName: "UpdatePhone",
			Handler:    _Auth_UpdatePhone_Handler,
		},
		{
			MethodName: "UpdateBirthday",
			Handler:    _Auth_UpdateBirthday_Handler,
		},
		{
			MethodName: "UpdateFb",
			Handler:    _Auth_UpdateFb_Handler,
		},
		{
			MethodName: "UpdateInsta",
			Handler:    _Auth_UpdateInsta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllUser",
			Handler:       _Auth_GetAllUser_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/auth.proto",
}
